### ISSUE TITLE
[Request] 请求更新Forge / Fabric 1.20(.1)

### ISSUE THREAD

**Issue by SkyEye-FAST** [kitUIN/ChatImage#10]
如题，似乎1.20并未对相应方面进行大改，适配应当不需要太多更改，可否考虑更新？

**Comment by kitUIN** [comment]
错误的,在我mixin的地方有很多修改,我得研究一下

**Comment by kitUIN** [comment]
@fabric已经发版 [1.1.6+1.20.1+fabric](https://github.com/kitUIN/ChatImage/releases/tag/1.1.6%2B1.20.1%2Bfabric)
forge版存在严重的bug,等待修复后发布 #8
