### ISSUE TITLE
[Bug] Crash Fabric 1.20.1

### ISSUE THREAD

**Issue by DeshiDesu** [kitUIN/ChatImage#11]
### Bug 描述

Crash when used command:
![2023-06-24_02 10 23](https://github.com/kitUIN/ChatImage/assets/120287925/293e4b61-299e-4fd2-bb51-a33bde573113)

### 复现问题的步骤

```plain text
1. Install modpack: https://legacy.curseforge.com/minecraft/modpacks/simplymc/files/4606168
2. Use /chatimage url command
3. Press enter then crash
```

### 日志记录

[latest.log](https://github.com/kitUIN/ChatImage/files/11855538/latest.log)

### Mod版本

ChatImage-1.1.6+1.20.1+fabric.jar

### 电脑系统|JAVA版本

java 17
windows 10

### 截图

[crash-2023-06-24_01.57.12-client.txt](https://github.com/kitUIN/ChatImage/files/11855537/crash-2023-06-24_01.57.12-client.txt)
Description: keyPressed event handler

java.lang.NoClassDefFoundError: okio/Buffer

**Comment by kitUIN** [comment]
看样子是我少打包了依赖，过俩天有空了修

**Comment by lgc2333** [comment]
same, will sub

**Comment by DeshiDesu** [comment]
> 看样子是我少打包了依赖，过俩天有空了修

Thank you :)

**Comment by kitUIN** [comment]
已修复,请下载1.1.7版本
下载地址:[MC百科](https://www.mcmod.cn/download/9111.html) [Github](https://github.com/kitUIN/ChatImage/releases/tag/1.1.7) [CurseForge](https://www.curseforge.com/minecraft/mc-mods/chatimage/files)
