### ISSUE TITLE
[新请求] 添加1.16.5forge版本

### ISSUE THREAD

**Issue by GADDQ** [kitUIN/ChatImage#13]
### Bug 描述

如题，希望能添加对1.16.5forge的支持！！！谢谢！！！

### 复现问题的步骤

```plain text
无
```

### 日志记录

不需要日志

### Mod版本

不需要填写这里

### 电脑系统|JAVA版本

java1.8.0_281

**Comment by kitUIN** [comment]
计划中

**Comment by GADDQ** [comment]
谢谢！！！

**Comment by GADDQ** [comment]
补充：这个mod的1.16.5版本应可在java8环境运行，否则很多整合包或者mod会产生java版本错误的崩溃问题！

**Comment by kitUIN** [comment]
已经完成

**Comment by GADDQ** [comment]
[bug] 新版本无法在java8u282环境加载

**Comment by kitUIN** [comment]
> [bug] 新版本无法在java8u282环境加载

已经修复,请使用1.2.1版本
