### ISSUE TITLE
[Bug] 服务器无法正常使用

### ISSUE THREAD

**Issue by MetaDecr** [kitUIN/ChatImage#15]
### Bug 描述

无法发送图片，在游戏中只能显示出对应的代码。可以确定服务器以及客户端都安装了相同版本的该模组。但是在单人游戏当中可以发出图片。

### 复现问题的步骤

```plain text
1.进入一个安装了该模组的服务器，拖入图片，可以看到显示出了代码，但发送出去之后仍然是代码
2打开一个单人存档，拖入图片，可以正常使用
```

### 日志记录

[latest.log](https://github.com/kitUIN/ChatImage/files/12344286/latest.log)

### Mod版本

1.1.7+1.20.1+0.14.22

### 电脑系统|JAVA版本

win11 17.0.3

### 截图

![图片](https://github.com/kitUIN/ChatImage/assets/142309164/7c960927-1d37-4a72-a680-1b22ac082873)
上面是单机情况下，下面是服务器中的情况
![图片](https://github.com/kitUIN/ChatImage/assets/142309164/70f24ce4-6142-445a-a49f-fd46491b4010)

**Comment by kitUIN** [comment]
该问题已经存在很久了,等待修复

**Comment by kitUIN** [comment]
Please use 1.1.8
