### ISSUE TITLE
[Feature request] 请求兼容gocqhttp转发的图片

### ISSUE THREAD

**Issue by Apricityx** [kitUIN/ChatImage#16]
我使用的是Chatbridge实现qq和mc的消息互通
gocqhttp转发到游戏内大概长这样：
[CQ:image,file=6decc70d3a5e03ffa1aca403934fe0da.image,subType=1,url=https://gchat.qpic.cn/gchatpic_new/437687850/726315307-2800984320-6DECC70D3A5E03FFA1ACA403934FE0DA/0?term=2&is_origin=0]
url= 后边即为图片地址

**Comment by kitUIN** [comment]
你要搜索的是不是：群服互联

**Comment by Apricityx** [comment]
> 你要搜索的是不是：群服互联
> https://www.mcmod.cn/class/4903.html

群服互联确实也是很好的一个mod
但Chatbridge也满足了其他不同的需求，且也有一定的用户量，如果可以同样解析来自Chatbridge的消息固然是很好的（你不觉得这很酷吗.jpg）

**Comment by kitUIN** [comment]
> > 你要搜索的是不是：群服互联
> > https://www.mcmod.cn/class/4903.html
> 
> 群服互联确实也是很好的一个mod
> 但Chatbridge也满足了其他不同的需求，且也有一定的用户量，如果可以同样解析来自Chatbridge的消息固然是很好的（你不觉得这很酷吗.jpg）

在此之前，等我先把奔溃问题修了🧐

**Comment by kitUIN** [comment]
由于我配置不好qqbot,暂时搁置

**Comment by Apricityx** [comment]
> 由于我配置不好qqbot,暂时搁置

如果方便的话我可以提供gohttp的搭建或者提供已搭载聊天互通的环境方便分析

**Comment by kitUIN** [comment]
> > 由于我配置不好qqbot,暂时搁置
> 
> 如果方便的话我可以提供gohttp的搭建或者提供已搭载聊天互通的环境方便分析

请加我QQ1585447424

**Comment by kitUIN** [comment]
已解决
