### ISSUE TITLE
Release 1.1.9 for Minecraft 1.19.x FORGE is not uploaded on neither CurseForge or Modrinth

### ISSUE THREAD

**Issue by KuryKat** [kitUIN/ChatImage#18]
When I saw that there was a 1.1.9 for 1.19.2 on Fabric I went looking for the Forge Version, sadly I couldn't find in neither CurseForge or Modrinth, only the 1.1.8

![image](https://github.com/kitUIN/ChatImage/assets/57152799/1617bb44-b0de-4af9-8dc9-42f5ae44eb39)

![image](https://github.com/kitUIN/ChatImage/assets/57152799/b3a5dac4-f0b6-457a-934c-5ed682556304)

but here on GitHub releases we have the 1.1.9 for said version, did you forget to upload the 1.19 version on the websites?

![image](https://github.com/kitUIN/ChatImage/assets/57152799/146d1237-fe8c-42c9-9d3b-fda8ce5d26fb)

Please fix if that's the reason, I want to update the mod on my modpack on CF and the application (CurseForge Launcher) needs the file be uploaded onto CF to be considered a valid version.

Side Note:

On CurseForge the latest file name for 1.19 is indeed 1.1.8
![image](https://github.com/kitUIN/ChatImage/assets/57152799/01f98339-ca31-4b5f-97cd-e46a2faddc25)

but on Modrinth... 
![image](https://github.com/kitUIN/ChatImage/assets/57152799/47e3ba5d-1faf-4fe1-922c-224c4f1acf0f)

Maybe you uploaded the wrong file onto CurseForge? or something? please check! ❤🥰

**Comment by kitUIN** [comment]
I find `1.1.9 with forge1.19.x ` have a bug
please use `1.1.10`
