### ISSUE TITLE
[Bug] Server pc

### ISSUE THREAD

**Issue by Ryuushen** [kitUIN/ChatImage#19]
### Bug 描述

Can't use command on server

### 复现问题的步骤

```plain text
Command doesn't work on Server

1.18.2 Forge
```

### 日志记录

![WindowsTerminal_mani61iQG3](https://github.com/kitUIN/ChatImage/assets/24853902/6e9fbcd4-4c12-4de3-beed-2646b68d53ae)

### 模组加载器

Forge

### 我的世界版本

1.18.x

### Mod版本

1.1.10

### 电脑系统|JAVA版本

JAVA 17

**Comment by Ryuushen** [comment]
![image](https://github.com/kitUIN/ChatImage/assets/24853902/c617a62c-b3cd-4a4d-8213-1de576f1e6a4)

**Comment by kitUIN** [comment]
Can you give me the command you used

**Comment by Ryuushen** [comment]
I tried all the command in the description

/chatimage url https://i.imgur.com/zy6Xcf1.png
/chatimage send Pizza https://i.imgur.com/zy6Xcf1.png

Those doesn't work , but it works when i use
[[CICode,url=https://i.imgur.com/zy6Xcf1.png,name=Image]]

**Comment by kitUIN** [comment]
This is due to no client command in forge 1.16+
I'll try a solution

**Comment by kitUIN** [comment]
I fix it

**Comment by Ryuushen** [comment]
You're the best, love the mod. Thank you
