### ISSUE TITLE
[Bug] [Fabric 1.20.1] ChatImage not working on server

### ISSUE THREAD

**Issue by donniebeck** [kitUIN/ChatImage#23]
The mod works fine in single-player, but on a Fabric 0.14.24 server, it does not. The commands work fine for formatting the command but all that appears in the chat is the CI code. 

The server and client have the same version of the mod installed: 1.1.12+1.20.1+fabric.

Does this mod require any additional ports to be open (other than 25565udp/tcp)?

**Comment by kitUIN** [comment]
![IMG_20240110_150430.jpg](https://github.com/kitUIN/ChatImage/assets/68675068/b98eeaec-2409-4e51-b4b6-0b12c9ac2165)

in my server，it's all right

**Comment by kitUIN** [comment]
Can you give more information?
do you use command? or just send CI Code  like `[[CICode,url=https://blog.kituin.fun/img/bg.png,name=Image]]`

**Comment by kitUIN** [comment]
long time no reply
