### ISSUE TITLE
[Bug] 1.20 Fabric 多人模式无法转换为图片

### ISSUE THREAD

**Issue by oldkingOK** [kitUIN/ChatImage#24]
### Bug 描述

单人模式可以展示图片，但是多人模式无法将链接转换成图片

### 复现问题的步骤

```plain text
1. 下载游戏：
- 1.20
- Fabric 0.15.3
- Fabric API 0.83.0+1.20
2. 下载mod
https://github.com/kitUIN/ChatImage/releases/tag/1.1.12
ChatImage-1.1.12+1.20+fabric.jar
3. 打开单人模式
输入并发送链接 [[CICode,url=https://blog.kituin.fun/img/bg.png,name=Image]]
——图片可正常展示
4. 连接任意服务器
输入并发送链接 [[CICode,url=https://blog.kituin.fun/img/bg.png,name=Image]]
——只显示白色文字，且鼠标移到上面时无法查看图片
```

### 日志记录

[in-server.log](https://github.com/kitUIN/ChatImage/files/13870101/in-server.log)
[in-single-player.log](https://github.com/kitUIN/ChatImage/files/13870102/in-single-player.log)

### 模组加载器

Fabric

### 我的世界版本

1.20

### Mod版本

1.1.12

### 电脑系统|JAVA版本

版本	Windows 11 专业版
版本	23H2
操作系统版本	22635.2921
体验	Windows Feature Experience Pack 1000.22684.1000.0

openjdk 17.0.8.1 2023-08-24 LTS
OpenJDK Runtime Environment Microsoft-8297089 (build 17.0.8.1+1-LTS)
OpenJDK 64-Bit Server VM Microsoft-8297089 (build 17.0.8.1+1-LTS, mixed mode)

### 截图

![image](https://github.com/kitUIN/ChatImage/assets/30453803/4d8f5b2e-6cda-4d23-93cf-ff87b6a0b0d5)
![image](https://github.com/kitUIN/ChatImage/assets/30453803/e30379b3-6328-47e1-af79-590685bb2f13)

**Comment by kitUIN** [comment]
也许是由其他因素造成的

**Comment by oldkingOK** [comment]
你好，感谢回复

> 可以尝试用命令chatimage来查看模组是否正常加载,正常加载的话应该会出现自动补全

确认mod已加载，chatimage命令会出现自动补全

![Pasted image 20240110193716](https://github.com/kitUIN/ChatImage/assets/30453803/826fbb2e-2162-43e6-b3f2-f51e63d5ede1)

我让朋友也测试了这个mod，他也遇到同样情况

你使用的fabric以及fabric-api版本是什么，以及方便上传一下你使用的mod.jar吗，我想进行更多尝试

**Comment by oldkingOK** [comment]
> 请添加我的QQ:1585447424

已申请

**Comment by kitUIN** [comment]
https://github.com/kitUIN/ChatImage/releases/tag/1.1.13
