### ISSUE TITLE
1.19.3 Fabric中黏贴快捷键导致游戏奔溃

### ISSUE THREAD

**Issue by ChocolaVanilla0305** [kitUIN/ChatImage#3]
1.19.3 Fabric中黏贴快捷键（Ctrl+V）导致游戏奔溃
“Signature is missing from textures payload”

**Comment by kitUIN** [comment]
之前是复制了什么
以及日志贴一下

**Comment by kitUIN** [comment]
呃呃，总得告诉一下怎么复现这个bug吧

**Comment by ChocolaVanilla0305** [comment]
不好意思给忘记了（
我去稍微翻一下

**Comment by kitUIN** [comment]
主要是复现这个bug的步骤是怎么样的，比如复制了什么图片，倒是粘贴的时候报错了

**Comment by ChocolaVanilla0305** [comment]
首先不排除我端的问题，我没有做这个模组单独加载的试验
1.19.3 - Fabric中剪切板复制图片或文字甚至不复制都会导致游戏未响应然后崩溃，
排除下来是此模组导致的（或许是未知的与其他模组不兼容？
[错误报告-2023-2-14_14.38.40.zip](https://github.com/kitUIN/ChatImage/files/10729472/-2023-2-14_14.38.40.zip)

**Comment by ChocolaVanilla0305** [comment]
“剪切板复制图片或文字甚至不复制都会导致游戏未响应然后崩溃”指的是打开聊天栏摁下“黏贴”热键“Ctrl+V”

**Comment by kitUIN** [comment]
报错信息太少了,不知道是哪里出了问题....

**Comment by ChocolaVanilla0305** [comment]
这里打包一份mods过来（？

**Comment by ChocolaVanilla0305** [comment]
Github传不上,
我发份MediaFire

**Comment by ChocolaVanilla0305** [comment]
https://www.mediafire.com/file/wxhuzwb39xxiz4q/mods.zip/file
然后我猜测可能是和tweakeroo部分功能冲突，
tweakeroo中的两个功能，
一个是”死亡后发送死亡坐标“
一个是“保存聊天草稿”

**Comment by ChocolaVanilla0305** [comment]
这个包没有大改原版的内容
是carpet，MaLi系列模组以及一些优化和个性化内容

**Comment by Moetazhxi** [comment]
Fabric 1.19.2 相同问题 +1，也是 Ctrl+V 粘贴时崩端，不过 Ctrl+C 复制并不会崩。
**但是经过单独测试，也就是客户端内只有 ChatImage 和 Fabric API 时，Ctrl+V 并不会崩。**

经过测试也不是 tweakeroo 导致的，因为我没有加入这个模组的时候粘贴也会崩。

我用 @ChocolaVanilla0305 发出来的模组试了一下，二分法挨个排查，发现是 [extended-armor-bars-1.2.1.jar](https://github.com/Slugstur/ExtendedArmorBars)，[CurseForge 链接](https://www.curseforge.com/minecraft/mc-mods/fabric-extended-armor-bars-forked) 这个模组导致崩端。
但不光单纯是这一个模组会导致崩，我用的端（[DarkRPG 整合包](https://www.curseforge.com/minecraft/modpacks/darkrpg)）里并没有这个模组，但是粘贴时也会崩。

怀疑可能是模组兼容性问题。

> 测试环境：
> Java 版本：18
> Fabric API 版本：fabric-api-0.74.0+1.19.3.jar
> ChatImage 版本：Fabric-1.19.3.ChatImage-1.1.0.jar

附上崩端报告：
[crash-2023-02-21_14.40.42-client.txt](https://github.com/kitUIN/ChatImage/files/10790626/crash-2023-02-21_14.40.42-client.txt)

**Comment by kitUIN** [comment]
初步鉴定为awt的问题
由于mc自带的glfw无法复制粘贴除了字符串以外的数据，故才用了awt
关于修复方式待进一步研究
