### ISSUE TITLE
[Feat] 支持原始 json 文本

### ISSUE THREAD

**Issue by hyplant** [kitUIN/ChatImage#30]
目前该模组使用原始 json 文本
`hoverEvent":{"action":"show_chatimage","contents":{"code":"[[CICode,url=https://blog.kituin.fun/img/bg.png,name=Image]]"}}`
来显示图片，但在命令/tellraw和成书中并不支持该聊天组件。
希望可以让这个聊天组件支持更多用法，例如在命令/tellraw，甚至成书和告示牌中使用。

**Comment by kitUIN** [comment]
其实不需要使用json，用单纯的CICode文本就行

`/tellraw @a ["","[[CICode,url=https://blog.kituin.fun/img/bg.png,name=Image]]"]`

- 关于json支持可以考虑
- 成书等待研究，若可行则会在未来版本加入
- 告示牌我记得有相关模组了吧

**Comment by hyplant** [comment]
CICode 会导致名称旁边出现括号，使文本无法很好地嵌入在一大段文字中。

**Comment by kitUIN** [comment]
将下个版本支持

- 自定义前后缀
- json
