### ISSUE TITLE
[Bug] 1.16.5 Forge图片发送存在缺陷

### ISSUE THREAD

**Issue by GADDQ** [kitUIN/ChatImage#33]
### Bug 描述

*已使用最新版*

问题①：发送本地文件时，如果文件名为纯英文gif则发送后以文本显示cicode全内容，不显示图片，暂不知url图片和其他格式是否有此问题
问题②：发送一个新的未在服务器缓存的gif时，会与服务器断开连接，显示：
*Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException:*
*Payload may not be larger than 32767 bytes*

### 复现问题的步骤

```plain text
*问题发生在整合包上，未在单mod端上尝试*

整合包客户端地址：https://www.123pan.com/s/LyQUjv-wVLN.html
整合包服务端地址：https://www.123pan.com/s/LyQUjv-gVLN.html
*注：这是直接打包的versions文件夹下的版本，不要用启动器安装，没用，全部解压放versions下面开版本隔离就行*
*服务端解压后，点击start.bat即可开服*

1、开一个该整合包的服务器
2、启动客户端，连接进服务器
3.1、发送纯英文名的gif，你会看到纯CIcode文本，而不是图片
3.2、发送一个中文名gif，与服务器断开连接，payload不可大于32767bytes
```

### 日志记录

[latest - client.log](https://github.com/kitUIN/ChatImage/files/14235154/latest.-.client.log)
[latest - server.log](https://github.com/kitUIN/ChatImage/files/14235160/latest.-.server.log)

### 模组加载器

Forge

### 我的世界版本

1.16.x

### Mod版本

最新版

### 电脑系统|JAVA版本

Windows 10 专业工作站版
Azul zulu 8u282

### 服务器版本

forge-1.16.5-36.2.41

### 截图

截图可能不能提供太大帮助，描述中已经详细解释

### 备注

无

**Comment by GADDQ** [comment]
可能是我有什么特殊的bug体质（

**Comment by kitUIN** [comment]
其实是我对低版本的研究不是很多，而且很少收到低版本的报错
等我研究一下

**Comment by kitUIN** [comment]
而且1.16.5还有一个没有客户端指令的问题没解决（

**Comment by kitUIN** [comment]
问题1是因为forge自己的url解析在服务端也有,我没mixin导致的
问题2 限制一下发包大小就行

**Comment by kitUIN** [comment]
请使用1.2.2版本
