### ISSUE TITLE
[Bug] 在如果服务端装有NoChatReports，则客户端发送的CICode等指令无法正常渲染为图片。

### ISSUE THREAD

**Issue by SheepXiu** [kitUIN/ChatImage#38]
### Bug 描述

在如果服务端装有NoChatReports，则客户端发送的CICode等指令无法正常渲染为图片。

### 复现问题的步骤

```plain text
在如果服务端装有NoChatReports，则客户端发送的CICode等指令无法正常渲染为图片。
```

### 日志记录

1

### 模组加载器

Fabric

### 我的世界版本

1.20.2

### Mod版本

1.2.3 fabric 1.20.4

### 电脑系统|JAVA版本

java21

**Comment by kitUIN** [comment]
请告知详细信息:
1. 服务端装有NoChatReports,客户端是否也安装NoChatReports
2. 客户端发送的CICode, 其他玩家还是发送者无法渲染为图片

**Comment by SheepXiu** [comment]
1. 两位测试者的客户端及连接的服务端均装有1.2.3 fabric 1.20.4的NoChatReports
2. 都不能渲染（客户端发送的CICode, 其他玩家和发送者都无法渲染为图片）
3. 无论CICode是本地图片还是网络图片，都无法正常渲染

**Comment by SheepXiu** [comment]
1. 两位测试者的客户端及连接的服务端均装有1.2.3 fabric 1.20.4的NoChatReports
2. 都不能渲染（客户端发送的CICode, 其他玩家和发送者都无法渲染为图片）
3. 无论CICode是本地图片还是网络图片，都无法正常渲染

**Comment by kitUIN** [comment]
> 1. 两位测试者的客户端及连接的服务端均装有1.2.3 fabric 1.20.4的ChatImage和Fabric-1.20.4-v2.5.0的NoChatReports
> 2. 都不能渲染（客户端发送的CICode, 其他玩家和发送者都无法渲染为图片）
> 3. 无论CICode是本地图片还是网络图片，都无法正常渲染
> 
> 试过纯净客户端（仅添加ChatImage），但是问题复现

试试1.2.4版本
