### ISSUE TITLE
[Bug] 发送超过32767字节的图片会被踢出

### ISSUE THREAD

**Issue by LittleChest** [kitUIN/ChatImage#39]
### Bug 描述

在其他人开放的局域网游戏（可能也包括`vanilla`服务器）发送超过32767字节（约32KB）的图片会被踢出，即使服务器并没有安装ChatImage

### 复现问题的步骤

```plain text
1. 进入服务器
2. 发送超过33KB的图片
```

### 日志记录

[latest.log](https://github.com/kitUIN/ChatImage/files/15081056/latest.log)

### 模组加载器

Fabric

### 我的世界版本

1.20.4

### Mod版本

1.2.3+1.20.4+fabric

### 电脑系统|JAVA版本

Windows 11
Zulu 21

### 服务器版本

vanilla 1.20.4（内置服务端）

### 截图

![image](https://github.com/kitUIN/ChatImage/assets/81231195/22a5bc6b-0367-4e12-9519-fad6115c09ee)

### 备注

在单人游戏或**自己开启的**局域网游戏不受此限制

在 Bukkit 服务器上也没有问题

**Comment by kitUIN** [comment]
此问题主要是因为模组修改了原版服务器读取上限
如果不加模组,就会报错
预计下个版本进行微调,限制分包长度在32767内

**Comment by LittleChest** [comment]
> 此问题主要是因为模组修改了原版服务器读取上限 如果不加模组,就会报错 预计下个版本进行微调,限制分包长度在32767内

后来我让对方安装了ChatImage，同样 :(

**Comment by kitUIN** [comment]
早上修,先睡觉力

**Comment by LittleChest** [comment]
好像没问题了 谢谢
