### ISSUE TITLE
[Bug] 在发送本地图片时（发送者）会被踢出游戏

### ISSUE THREAD

**Issue by Emerald-Rail** [kitUIN/ChatImage#40]
### Bug 描述

在发送本地图片时（发送者）会被踢出游戏

### 复现问题的步骤

```plain text
1.打开游戏（1.19.2Fabric）
2.进入一个服务器
3.发送本地图片
```

### 日志记录

[latest.log](https://github.com/kitUIN/ChatImage/files/15333435/latest.log)

### 模组加载器

Fabric

### 我的世界版本

1.19.2

### Mod版本

1.2.3

### 电脑系统|JAVA版本

Windos 10，Java 17

### 服务器版本

1.19.2 Fabric 0.15.10

### 截图

![image](https://github.com/kitUIN/ChatImage/assets/168388244/d7f691bf-02cb-48a3-8639-9e24d572f4e4)

**Comment by kitUIN** [comment]
与 #39 是同一个问题
马上修

**Comment by Emerald-Rail** [comment]
> 与 #39 是同一个问题 马上修

**Comment by kitUIN** [comment]
已经更新
