### ISSUE TITLE
[Bug] 超过33kb图片踢出服务器

### ISSUE THREAD

**Issue by meishiffx** [kitUIN/ChatImage#41]
### Bug 描述

在服务器中超过32767字节图片被踢出

### 复现问题的步骤

```plain text
1. 进入服务器
2. 发送超过33KB的图片
```

### 日志记录

[latest.log](https://github.com/user-attachments/files/15838816/latest.log)

### 模组加载器

Forge

### 我的世界版本

1.19.1/1.19.2

### Mod版本

ChatImage-1.2.3+1.19.x+forge

### 电脑系统|JAVA版本

win11
Jdk21

### 备注

我看到了#39，但是forge没有1.2.4版本。另外我建议不要硬编码，生成配置文件让玩家自己配置。

**Comment by kitUIN** [comment]
看来是全部版本都有问题,等周末我全修一边

**Comment by kitUIN** [comment]
已经更新
