### ISSUE TITLE
[Bug] 无法发送在游戏内截图的本地图片 提示包过大

### ISSUE THREAD

**Issue by jianchihu-leader** [kitUIN/ChatImage#46]
### Bug 描述
已经更新到1.2.4版本任然出现
发送部分本地图片 客户端会显示连接丢失 服务端报错 

### 复现问题的步骤

```plain text
在MC fabric 1.20.1客户端中 使用F2截图
正常发送所截图的图片
会提示连接丢失 而被踢出服务器

```

### 日志记录

服务端
[Server] [17:39:02] [Server thread/INFO]: <IK_Maple_Star> [[CICode,url=file:///E:\Minecraft\纯净整合包\【1.20.1】IK-M 生电整合包 V.2.0\versions\1.20.1_Fabric_MOF-Server_IK-Maple\screenshots\2024-07-06_00.07.39.png]]
[Server] [17:39:02] [Server thread/INFO]: IK_Maple_Star lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
[Server] [17:39:02] [Server thread/INFO]: IK_Maple_Star left the game。

### 模组加载器

Fabric

### 我的世界版本

1.20.1

### Mod版本

1.2.4

### 电脑系统|JAVA版本

win11  zulu22

### 服务器版本

fabric-server-launch-1.20.1

**Comment by jianchihu-leader** [comment]
补充……让后台再做了一次实验 似乎与VC无关

**Comment by jianchihu-leader** [comment]
我可能需要和您对照一些 本模组1.2.4文件 的sha1值
642b3472a056e32848c4d1da8fdd3306066ca9b7
这是我从modrinth下载的版本，目前测试的又出现了无论如何都会报错的场景，报错内容与上述相同

**Comment by kitUIN** [comment]
与 https://github.com/kitUIN/ChatImage/issues/42 一样吗?

**Comment by jianchihu-leader** [comment]
非常抱歉，我通过后台发现 之前所遇到通过VC端的问题是表述错误，是由于您的模组又识别文件ID的功能 导致某些情况显示上传成功了但实际根本没有上传

实际遇到的问题是 在使用客户端和服务端同样使用1.2.4的时候 任会出现包过大报错

**Comment by jianchihu-leader** [comment]
> 与 #42 一样吗?

这个是1.2.3的模组版本，我目前是已经更新了最新的模组 但任然遇到同样的问题

**Comment by jianchihu-leader** [comment]
我更正了一下问题

**Comment by kitUIN** [comment]
奇怪,我这里测试正常,你使用的图片能否发我

**Comment by jianchihu-leader** [comment]
[Uploading 测试用图.zip…]()

**Comment by jianchihu-leader** [comment]
si……好像有这个可能
我使用别的图片就能正常发送，但这些就不行
这些都是使用MC F2截图的

**Comment by kitUIN** [comment]
> Uploading 测试用图.zip…

不是....图呢

**Comment by kitUIN** [comment]
https://cowtransfer.com/s/23685a82cf484c 点击链接查看 [ ChatImage-1.2.5+1.20.1+fabric.jar ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 9eceoh 查看；
我这里先放一个调小包限制的测试版本,你试试先

**Comment by jianchihu-leader** [comment]
抱歉，我不太会用github 我是使用提交页面的"add files" 似乎是我操作问题 我重新发一下
[测试用图.zip](https://github.com/user-attachments/files/16164655/default.zip)

测试了一下 您提供的1.2.5是可以正常使用的
大概3M的文件 显示分了137个包 不过确实可以使用了

**Comment by jianchihu-leader** [comment]
如果又发送失败的话……就 您在MC Fabric 1.20.1 客户端中使用F2截图，应该可以做到近似的效果
