### ISSUE TITLE
[适配问题] mc-qqbot(群服互联)

### ISSUE THREAD

**Issue by HL5570** [kitUIN/ChatImage#47]
### Bug 描述

在qq群发图片，这是原本的链接https://multimedia.nt.qq.com.cn/download?appid=1407&amp&fileid=CgozMTY2MzI2OTQ0EhSgy40K7R49J1QwWk6TVDnZcvDCjRjapQMg_wooitSD8b6ZhwNQgL2jAQ&amp&spec=0&amp&rkey=CAISKKSBekjVG1fMwnePyWN7SpUiYdgno34HLewhnzVBOCqsni7cPnFtNx4
是可以正常访问的
但是此模组识别出的链接是带；号的
https://multimedia.nt.qq.com.cn/download?appid=1407&amp;fileid=CgozMTY2MzI2OTQ0EhSgy40K7R49J1QwWk6TVDnZcvDCjRjapQMg_wooitSD8b6ZhwNQgL2jAQ&amp;spec=0&amp;rkey=CAISKKSBekjVG1fMwnePyWN7SpUiYdgno34HLewhnzVBOCqsni7cPnFtNx4
然后qq群发的图片就相当于无效链接

### 复现问题的步骤

```plain text
Qq群发送的图片,链接识别有问题
https://multimedia.nt.qq.com.cn/download?appid=1407&amp;fileid=CgozMTY2MzI2OTQ0EhSgy40K7R49J1QwWk6TVDnZcvDCjRjapQMg_wooitSD8b6ZhwNQgL2jAQ&amp;spec=0&amp;rkey=CAISKKSBekjVG1fMwnePyWN7SpUiYdgno34HLewhnzVBOCqsni7cPnFtNx4
会加上分号导致无法访问, 把分号改成&
可以正常访问。
```

### 日志记录

无

### 模组加载器

Fabric

### 我的世界版本

1.19.3/1.19.4

### Mod版本

1.20.4 fabric

### 电脑系统|JAVA版本

w11 17

**Comment by haishen668** [comment]
https://www.yuque.com/haishen668/xinxinbot/nmzln5g6m1b8558o#zKlCn
我也写了一个类似的插件但是好像没有问题？

**Comment by GADDQ** [comment]
我觉得你应该去找群服互联的作者，而不是来这里反馈。。

**Comment by HL5570** [comment]
MC-BOT没处理转义字符
