### ISSUE TITLE
服务端报错

### ISSUE THREAD

**Issue by Aegleseekers** [kitUIN/ChatImage#5]
### Bug 描述

只要把此mod放在服务端内，服务端就不能成功开启，也就是说 我把这个mod从服务端内删除服务端就会正常开启。

### 复现问题的步骤

```plain text
就是在服务端内添加或删除此mod
```

### 日志记录

[latest.log](https://github.com/kitUIN/ChatImage/files/11109997/latest.log)
[debug-1.log.gz](https://github.com/kitUIN/ChatImage/files/11109999/debug-1.log.gz)

### Mod版本

1.1.4+1.19.2+Forge

### 电脑系统|JAVA版本

jdk-17.0.1

**Comment by kitUIN** [comment]
已经修复,请下载新版本1.1.5+1.19.2+Forge
[⬇️CurseForge](https://www.curseforge.com/minecraft/mc-mods/chatimage) · [⬇️MC百科](https://www.mcmod.cn/class/9111.html)
