### ISSUE TITLE
可否支持渲染hoverEvent中show_text的CICode

### ISSUE THREAD

**Issue by meng877** [kitUIN/ChatImage#50]
举一例使用场景：
服务器没有强制所有人安装ChatImage mod,
从服务器交流群同步图片到服务器内(带有很长一段url)，使用hoverEvent中show_text
来兼顾使用mod玩家(显示图片)
以及未使用mod玩家(显示文本"[[CICode,url=图片url]]")
避免因CICode过长而影响阅读

**Comment by kitUIN** [comment]
显示图片和显示文字只能选择一个，不能针对是否安装模组进行切换

**Comment by kitUIN** [comment]
感觉可以实现

**Comment by kitUIN** [comment]
不过目前在调整多版本结构，新功能得稍后写

**Comment by kitUIN** [comment]
Support in 1.3.0

**Comment by meng877** [comment]
fabric 1.21.0 mod版本 1.3.0 依然无法使用此功能
![image](https://github.com/user-attachments/assets/c53af638-c026-4660-8756-cf548ac703c9)

**Comment by meng877** [comment]
log
[latest.log](https://github.com/user-attachments/files/18046158/latest.log)
