### ISSUE TITLE
Not stripping url arguments for discord images

### ISSUE THREAD

**Issue by oskarbukovsky** [kitUIN/ChatImage#51]
It looks like chatimage ignore parameters in url and for discord images it doesnt work
![image](https://github.com/user-attachments/assets/61489c99-7307-4e5b-ab4b-dc7053c4eaf5)

**Comment by kitUIN** [comment]
could you give me raw url?

**Comment by oskarbukovsky** [comment]
Examples:

![image](https://github.com/user-attachments/assets/bb31a40d-4a75-4741-9009-763c86b017d6)
https://media.discordapp.net/attachments/1243302804802633728/1263505132276940860/image.png?ex=669a7a5a&is=669928da&hm=9ee4b06fc189006b7a81e9730649a4cea750cc87d12149ec18008466c5431512&=&format=webp&quality=lossless


![image](https://github.com/user-attachments/assets/b8f8fb05-d0e5-4e51-8c34-714b00b6a558)
https://cdn.discordapp.com/attachments/1243302804802633728/1263506347371135048/IMG_20240718_164152.jpg?ex=669a7b7c&is=669929fc&hm=05e84327f7171b3ce5fe3b5c42e1ecc7a74bc50988228faef40e8a75e6b08cf4&


![image](https://github.com/user-attachments/assets/f502fa1b-56f5-48f1-8918-18f0412039ef)

**Comment by kitUIN** [comment]
minecraft version is ?

**Comment by oskarbukovsky** [comment]
Minecraft 1.20.1
Forge 47.3.1
ChatImage 1.2.4+1.20.1+forge

**Comment by kitUIN** [comment]
now, not support `url with parameters`

**Comment by oskarbukovsky** [comment]
Any chance to adding suport for parameters to mod? We are using discordsrv and it will be super cool to not switch windows and enjoy image content ingame.

**Comment by kitUIN** [comment]
It is very difficult to determine the valid length of the url when the url with parameters is in a sentence.

A better way is for discordsrv to support CICode usage

**Comment by oskarbukovsky** [comment]
Why just not to look at url as one word from http/etc. and try first if it is a valid image response else use current behavior?

**Comment by oskarbukovsky** [comment]
I'll try to make feature suggestion od discordsrv github, but i think not that much people will use CICode functionality. So probably time to find some workaround on discord to download and upload images elsewhere and send link to them into channel as bot, idk :(

**Comment by kitUIN** [comment]
I'll try to implement a url with parameters

**Comment by kitUIN** [comment]
Support in 1.3.0
