### ISSUE TITLE
[BUG] 装了ChatImage后会使聊天区的链接无法点击转跳

### ISSUE THREAD

**Issue by GADDQ** [kitUIN/ChatImage#52]
如题
版本：1.16.5-Forge-1.2.3
JAVA: Zulu java 8u281
OS: Windows 10 & Arch Linux
另一个bug是你issue的模版没了（

**Comment by GADDQ** [comment]
![image](https://github.com/user-attachments/assets/a4e2954e-2bc8-4686-9e19-1d1515752180)

**Comment by kitUIN** [comment]
因为forge自带的链接解析跟我的url图片解析冲突了，所以我把它的hook掉了

**Comment by kitUIN** [comment]
不能
这个forge自带的链接解析优先级太高了
整个关掉才能正常解析图片链接

**Comment by GADDQ** [comment]
那能否通过自行实现一个点击链接转跳浏览器解决问题呢？

**Comment by kitUIN** [comment]
可行,但是这非本模组内容

**Comment by kitUIN** [comment]
该功能将于1.4.0上线
