### ISSUE TITLE
[冲突] 和服务端的mod：NoChatReports-FABRIC-1.21-v2.8.0冲突

### ISSUE THREAD

**Issue by xizhuxz** [kitUIN/ChatImage#56]
### Bug 描述

游戏版本是1.21

### 复现问题的步骤

```plain text
1
```

### 日志记录

1

### 模组加载器

Fabric

### 我的世界版本

1.20.2

### Mod版本

1.2.5

### 电脑系统|JAVA版本

win10 21

**Comment by kitUIN** [comment]
Support in 1.3.0
