### ISSUE TITLE
[Bug] 该模组导致部分原始JSON文本异常

### ISSUE THREAD

**Issue by hyplant** [kitUIN/ChatImage#6]
### Bug 描述

forge 1.19.4，模组版本1.1.5
在聊天栏中使用部分原始JSON文本时，某些元素会在聊天消息的最后被重复，卸载这个模组是不会发生这种情况。

### 复现问题的步骤

```plain text
1. 安装模组，载入一个世界
2. 放置一个结构方块，调到数据模式，在里面输入"消息"
3. 站在结构方块上运行命令/tellraw @a [{"color":"#ffffff","text":"[SERVER] "},{"nbt":"metadata","block":"~ ~-1 ~","interpret":true}]
4. 得到的聊天消息是[SERVER] 消息消息

5. 卸载模组时得到的聊天消息是[SERVER] 消息
```

### 日志记录

[latestlog.txt](https://github.com/kitUIN/ChatImage/files/11238516/latestlog.txt)

### Mod版本

mod1.1.5
mc1.19.4
forge45.0.43

### 电脑系统|JAVA版本

android12/pojav9939093/pojav专用java17.0.7

### 截图

![Screenshot_20230415-140152_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/86937725/232188930-f56db82e-4522-4e1e-a26c-4f8fe58dd536.png)
![Screenshot_20230415-140316_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/86937725/232188938-7dee3780-00d2-468c-8578-3840548375ac.png)
![Screenshot_20230415-140406_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/86937725/232188946-47074425-56c6-4d76-927e-37639c5c4adb.png)
![Screenshot_20230415-140420_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/86937725/232188952-63002862-a67b-4ad9-8918-196786d38d0b.png)

**Comment by kitUIN** [comment]
已修复,请使用1.1.6版本
