### ISSUE TITLE
[Bug] 在1.21.4图片无法加载

### ISSUE THREAD

**Issue by JulyYoLo** [kitUIN/ChatImage#60]
如题，在1.21.4的Fabric版本中
ChatImage-1.3.0+1.21.2+fabric.jar图片无法正常显示
具体情况为 游戏内显示图片加载中，100%  如图 图片由[CICode]格式发送
![f9b313404941e0f902a97d53020aa0ee](https://github.com/user-attachments/assets/6b4cf476-6949-439a-b517-e5d3770d318e)

以上消息在1.21.1正常显示  版本为 ChatImage-1.2.5+1.21+fabric.jar

单人情况下，在游戏内使用/chatimage url命令 也无法正常显示，如图
![67c28dc68320c8a593fbe7ad683a7e21](https://github.com/user-attachments/assets/309d696b-0d52-4e53-89aa-ed216a3f5326)

使用的指令为
/chatimage url https://bu.dusays.com/2024/09/20/66ec69f997ac8.gif

**Comment by JulyYoLo** [comment]
在1.21.1的ChatImage-1.2.5 Fabric版本下
正常显示的画面为
![Cache_-2ed0ac0bbd76b972](https://github.com/user-attachments/assets/c1b55056-9c91-4db5-8d1d-e67a5d09810a)

前面的[QQ]是因为使用了插件将QQ图片消息通过python转化为[CICode]格式
但在更新至1.21.4的1.3.0版本就无法正常显示

**Comment by kitUIN** [comment]
能否上传一下日志

**Comment by JulyYoLo** [comment]
[latest.log](https://github.com/user-attachments/files/18125736/latest.log)
好的，感谢回复

**Comment by kitUIN** [comment]
暂时不支持1.21.4,等我单独适配一下

**Comment by JulyYoLo** [comment]
> 暂时不支持1.21.4,等我单独适配一下

好的，期待适配

**Comment by kitUIN** [comment]
https://modrinth.com/mod/chatimage/version/WT4gtL8z
新版试一下

**Comment by JulyYoLo** [comment]
> Owner

![78fb8bfcc80082bbd6edb02f220ab4a2](https://github.com/user-attachments/assets/c7edb11b-58f6-4e95-a350-9a1b0be369fe)
感谢修复！已经正常使用
